### ISSUE TITLE
USB Serial Midi / RTPMidi passthrough to GPIO / USB / RTP midi TX

### ISSUE THREAD

**Issue by skadarnold** [dwhinham/mt32-pi#296] opened 2022-07-02 03:48 UTC
More passthrough options between different protocols could be very useful. 

For example, the Vintage Serial / Raspberry Pi USB option is great, but it would also be useful to be able to passthrough the receive data to both the GPIO TX, RTPMidi respectively to be able to connect external synths. Or also from RTPMidi passthrough to GPIO / USB midi.

There might be other routing options to consider as well, but I think this could add some flexibility.

**Comment by skadarnold** [comment] 2022-07-03 20:12
As I am looking through the code for this, I might be able to help contribute to these enhancements if it is not currently being worked on elsewhere.

**Comment by dwhinham** [comment] 2022-07-03 23:50
Closing as:
- the issue template was ignored
- this is a duplicate of #138
- the feature is already being worked on

**Closed by dwhinham** 2022-07-03 23:50 UTC
Labels: enhancement
